### PR TITLE
Added bower.json.

### PR DESCRIPTION
**Pull request by codekipple**
Would you guys consider supporting [bower](http://bower.io/)?

I was trying to install FlexSlider via bower but was unable to set it to a particular version.

### CODE REVIEW

**Comment by kraftner** [comment]
...almost 1/2 years later...still waiting...

**Comment by climboid** [comment]
The easiest thing is to fork the library and create your own bower component.

**Comment by jaylinski** [comment]
+1

**Comment by mpdude** [comment]
What about adding additional tags for current versions that are not prefixed with "version/"? Would that work for bower?

**Comment by doublemarked** [comment]
Would love to see this also. Currently bower will find and install the lib, but the lack of a bower.json is breaking other tools like wiredep.

**Comment by litchfield** [comment]
Come on guys, you can make thousands of people happy here with a single click of your mouse.

**Comment by adriantomic** [comment]
+1 for this. Wiredep won't work without a bower.json.

**Comment by Krigu** [comment]
+1. Would be really great!

**Comment by mpdude** [comment]
Only 964 more :+1: needed to get this merged. Spread the word!

**Comment by matstars** [comment]
LETS DO THIS

**Comment by Bersam** [comment]
+1 for pull-request, but just as a workaround, you can override main property in your bower.json:
install FlexSlider like this:
bower install --save https://github.com/woothemes/FlexSlider.git
then override main property for wiredep like this:
```json
...
"overrides": {
  "FlexSlider": {
    "main": [
      "jquery.flexslider.js",
      "flexslider.css"
    ]
  }
}
...
```

**Comment by Kanti** [comment]
+1 :+1:

**Comment by dragosmocrii** [comment]
+1 Voted!

**Comment by dragosmocrii** [comment]
@Bersam 

Can you please provide more detailed instructions how to make this work? I am new to bower and wiredep, so am unsure where to add the overrides parts exactly. Thanks!

**Comment by Bersam** [comment]
@dragosmocrii here's a sample of working bower.json with overrides for FlexSlider.
https://gist.github.com/Bersam/8f3747af74f3aab11926

**Comment by dragosmocrii** [comment]
@Bersam 

Thank you!

**Comment by octavioamu** [comment]
I added this bower but would overwrite the bower.json. Just adding here because some examples are missing the dependencies. 

```
{
  "name": "flexslider",
  "version": "1.3.15",
  "main": [
    "./jquery.flexslider-min.js",
    "./flexslider.css"
  ],
  "ignore": [],
  "dependencies": {
    "jquery": "~2"
  }
}
```

**Comment by jeffikus** [comment]
Hi guys, I've bumped this into the 2.6.0 release, you'll see it's focused on package managers in the release description I've planned! Thanks for your continued patience!

**Comment by Soullivaneuh** [comment]
@jeffikus why adding all `bower_components` directory? This should be ignored.

**Pull request closed without merging**
