### PR TITLE
Disable text select on thumbnails

### PR DESCRIPTION
**Pull request by Ninos**
See also your examples with thumbnails (click on a thumbnail):
http://flexslider.woothemes.com/thumbnail-controlnav.html
http://flexslider.woothemes.com/thumbnail-slider.html

### CODE REVIEW

**Comment by Ninos** [comment]
My PR disables text select on thumbnails, so you'll not get following blue layer on image click anymore (see screenshot, second slider thumbnail).
screenshot 13

**Comment by jeffikus** [comment]
Interesting, ok that makes sense, I'll test this further on Monday @Ninos is this browser specific or in all of them?

**Comment by Ninos** [comment]
Hmm seems that just Firefox has this problem..

**Comment by jeffikus** [comment]
Ok, thanks for clarifying, I'm noticing more and more issues specific to firefox :(

**Pull request closed without merging**
