### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by jeffikus** [comment]
While Bower does not explicitly require a version number, I'll be keeping it in for specification sake.

**Comment by kkirsche** [comment]
For spec sake? It says to leave it out.

**Comment by jeffikus** [comment]
@kkirsche http://bower.io/docs/creating-packages/

**Comment by kkirsche** [comment]
Doesn't matter what that says if the spec says something that's really the ultimate authority.

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by jeffikus** [comment]
@kkirsche i hear what you are saying, but I'm still not going to remove it unless it breaks something. There is absolutely no harm in leaving a version number in there. It is a manifest file which can give you a simple view into what the current version is.

**Pull request closed without merging**
