### PR TITLE
Added RTL Support

### PR DESCRIPTION
**Pull request by layalk**
Added RTL support to the slider.

### CODE REVIEW

**Comment by jeffikus** [comment]
Hi there, thanks, I'll test this and merge if it passes!

**Comment by NabiKAZ** [comment]
This is for 1 years ago, Why don't accept this pull request, I need it.

**Comment by thomasguillot** [comment]
Seems to work as expected. Thoughts @jeffikus?

**Comment by jeffikus** [comment]
@thomasguillot thanks for testing! will merge into 2.7.0 this afternoon 👯

**Comment by jeffikus** [comment]
Merged into the release branch 2.7.0 :)

**Comment by layalk** [comment]
Thanks a lot!

**Pull request closed without merging**
